export function catalogModuleUrl(file,base=import.meta.url){const url=new URL(file,base),version=new URL(base).searchParams.get('v');if(version)url.searchParams.set('v',version);return url.href;}
const [data,drafts,imports]=await Promise.all(['./commerce-catalog-data.js','./commerce-catalog-draft.js','./commerce-catalog-import.js'].map(file=>import(catalogModuleUrl(file))));
const {PURPOSES,ICONS,UNITS,PROFESSION_TEMPLATES,decimal,scaled,quantityText,moneyMinor,safePhotoUrl,itemStock,itemProblem,addLines,bundleLine,detachBundle,evaluateCart,buildIntent,repeatPurchase,filterItems,lineErrors,friendlyError}=data;
const {CONTEXT_FIELDS,createDraftStore,receiptMatches,deepFreeze}=drafts;
const {IMPORT_FIELDS,guessColumns,previewImport,validateItem,decodeCatalogFile}=imports;

const minorText=value=>Number.isSafeInteger(value)&&value>0?String(BigInt(value)/100n)+'.'+String(BigInt(value)%100n).padStart(2,'0'):'';
const money=value=>Number.isSafeInteger(value)&&value>0?new Intl.NumberFormat('ru-RU').format(BigInt(value)/100n)+','+String(BigInt(value)%100n).padStart(2,'0')+' ₽':'Цена не указана';
const clone=value=>JSON.parse(JSON.stringify(value));
const paths={box:'M4 7 12 3 20 7v10l-8 4-8-4ZM4 7l8 4 8-4M12 11v10',bottle:'M9 3h6v4H9ZM9 7l-2 4v9h10v-9l-2-4M7 13h10',jar:'M6 4h12v4H6ZM5 8h14v12H5ZM5 13h14',tube:'M8 3h8l2 15H6ZM8 18h8v3H8Z',spray:'M9 3h7v4H9ZM9 7l-3 5v9h12v-9l-2-5M16 3h4v3M6 13h12',brush:'M8 3h8v8H8ZM8 6h8M12 11v10M10 21h4',scissors:'M9 14 19 4M9 10 19 20M4 7a3 3 0 1 0 6 0 3 3 0 1 0-6 0M4 17a3 3 0 1 0 6 0 3 3 0 1 0-6 0',ball:'M3 12a9 9 0 1 0 18 0 9 9 0 1 0-18 0M3 12h18M12 3c-5 5-5 13 0 18M12 3c5 5 5 13 0 18',roller:'M5 4h14v16H5ZM5 4c3 3 11 3 14 0M5 20c3-3 11-3 14 0M9 7v10M15 7v10',mat:'M5 4h14v16H5ZM5 8h14M5 12h14M5 16h14',drop:'M12 3c-2 4-7 8-7 12a7 7 0 0 0 14 0c0-4-5-8-7-12ZM8 15c0 3 2 4 4 4'};
function node(tag,className='',text=''){const el=document.createElement(tag);if(className)el.className=className;if(text!==undefined)el.textContent=text;return el;}
function button(text,className='cc-button'){const el=node('button',className,text);el.type='button';return el;}
function icon(item){const wrap=node('span','cc-icon');wrap.setAttribute('aria-hidden','true');const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('fill','none');svg.setAttribute('stroke','currentColor');svg.setAttribute('stroke-width','1.65');svg.setAttribute('stroke-linecap','round');svg.setAttribute('stroke-linejoin','round');const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',paths[item?.icon]||paths.box);svg.append(path);wrap.append(svg);return wrap;}
function image(item){const url=safePhotoUrl(item?.photo_url);if(!url)return icon(item);const wrap=node('span','cc-photo');const img=node('img');img.src=url;img.alt='';img.loading='lazy';img.referrerPolicy='no-referrer';img.addEventListener('error',()=>wrap.replaceWith(icon(item)),{once:true});wrap.append(img);return wrap;}
function field(label,control){const el=node('label','cc-field');el.append(node('span','',label),control);return el;}
function input(label,value='',type='text'){const control=node('input');control.type=type;control.value=String(value??'');control.setAttribute('aria-label',label);return control;}
function selector(label,rows,value,emptyLabel){const el=node('select');el.setAttribute('aria-label',label);if(emptyLabel!==undefined){const option=node('option','',emptyLabel);option.value='';el.append(option);}for(const row of rows){const option=node('option','',row.label??row.name??row.id);option.value=String(row.id);option.disabled=row.disabled===true;el.append(option);}if(value&&!rows.some(row=>String(row.id)===String(value))){const option=node('option','','Недоступно — проверьте выбор');option.value=String(value);option.disabled=true;el.append(option);}el.value=value||'';return el;}

/** Presentation only. Root owns DB/auth/role checks, response attestation and release. */
export function attachCommerceCatalog(container,options={}){
 if(!container)throw new TypeError('Catalog container required');
 let state=clone(options.state||{}),context={},lines=[],pending=null,storageCorrupt=false,storageFailure=false,alive=true,epoch=0,busy=false,error='',notice='',serverErrors={},selected=null,importState=null,editor=null,auxDraft=null;
 const filters={search:'',category:'',purpose:'',favoritesOnly:false};let visibleLimit=60;
 const scope=()=>({orgId:state.orgId,actorId:state.actorId,sessionKey:state.sessionKey});
 const token=()=>({...scope(),epoch,revision:state.revision,clientId:context.clientId});
 const current=(t,checkRevision=true)=>alive&&t.epoch===epoch&&t.orgId===state.orgId&&t.actorId===state.actorId&&t.sessionKey===state.sessionKey&&(!checkRevision||t.revision===state.revision)&&t.clientId===context.clientId;
 const fullState=()=>({...state,...context});
 const canManage=()=>state.canManage===true&&['owner','admin'].includes(state.role);
 const canWrite=()=>canManage()&&state.canWrite===true&&state.capabilities?.writes_enabled===true&&!pending&&!storageCorrupt&&!busy;
 let storage=options.storage;
 if(storage===undefined){try{storage=globalThis.localStorage;}catch{storage=null;}}
 const store=createDraftStore(storage,scope());
 const saved=store.load();storageCorrupt=saved?.corrupt===true;
 for(const key of CONTEXT_FIELDS)context[key]=state.context?.[key]??state[key]??null;
 if(saved&&!storageCorrupt){const explicitClient=Object.hasOwn(state.context||state,'clientId')&&context.clientId!==null;
  if(saved.pending||!explicitClient||context.clientId===saved.context.clientId){context={...saved.context};lines=saved.lines;pending=saved.pending?deepFreeze(saved.pending):null;}
 }
 if(pending?.kind==='sale'){const p=pending.payload;context={clientId:p.p_client_account,bookingId:p.p_booking,sellerId:p.p_seller,paymentMethod:p.p_payment_method,paymentAccountId:p.p_payment_account,warehouseId:p.p_lines[0]?.warehouse_id||null};}
 context.paymentMethod=context.paymentMethod||'cash';
 const shell=node('section','commerce-catalog');shell.setAttribute('aria-label','Каталог товаров и корзина');
 const head=node('div','cc-head'),title=node('h3','','Товары'),actions=node('div','cc-actions');head.append(title,actions);
 const status=node('p','cc-status');status.setAttribute('role','status');status.setAttribute('aria-live','polite');
 const alert=node('p','cc-error');alert.setAttribute('role','alert');
 const tools=node('div','cc-tools'),search=input('Поиск товара','','search');search.placeholder='Название, артикул или вариант';
 const category=selector('Категория',[],'','Все категории'),purpose=selector('Назначение',Object.entries(PURPOSES).map(([id,label])=>({id,label})),'','Любое назначение');
 const favorite=button('Избранное');favorite.setAttribute('aria-pressed','false');tools.append(search,category,purpose,favorite);
 const grid=node('div','cc-grid'),catalog=node('div','cc-catalog'),list=node('div','cc-list'),bundleList=node('div','cc-bundles'),cart=node('aside','cc-cart');cart.setAttribute('aria-label','Корзина');catalog.append(list,bundleList);grid.append(catalog,cart);
 const settings=node('details','cc-settings');settings.append(node('summary','','Клиент и детали продажи'));const fields=node('div','cc-context');settings.append(fields);
 const dialog=node('dialog','cc-dialog');dialog.setAttribute('aria-label','Карточка товара');
 shell.append(head,status,alert,tools,settings,grid,dialog);container.replaceChildren(shell);
 search.addEventListener('input',()=>{filters.search=search.value;visibleLimit=60;renderCatalog();});category.addEventListener('change',()=>{filters.category=category.value;visibleLimit=60;renderCatalog();});purpose.addEventListener('change',()=>{filters.purpose=purpose.value;visibleLimit=60;renderCatalog();});favorite.addEventListener('click',()=>{filters.favoritesOnly=!filters.favoritesOnly;favorite.setAttribute('aria-pressed',String(filters.favoritesOnly));renderCatalog();});
 list.addEventListener('keydown',event=>{if(!['ArrowDown','ArrowUp','Home','End'].includes(event.key))return;const rows=[...list.querySelectorAll('[data-catalog-open]')];if(!rows.includes(document.activeElement))return;event.preventDefault();const index=rows.indexOf(document.activeElement);rows[event.key==='Home'?0:event.key==='End'?rows.length-1:(index+(event.key==='ArrowDown'?1:-1)+rows.length)%rows.length]?.focus();});
 function persist(){const ok=store.save({context,lines,pending});storageFailure=!ok;if(!ok)notice='Черновик не сохранён на устройстве. До восстановления хранения продажа не отправляется.';options.onDraftChange?.({scope:scope(),saved:ok,pending:Boolean(pending),lineCount:lines.length});return ok;}
 function report(value){error=typeof value==='string'?value:friendlyError(value);options.onError?.({scope:scope(),error:value});renderStatus();}
 function renderStatus(){status.textContent=storageCorrupt?'Защитные данные на устройстве повреждены. Проверьте историю продаж перед восстановлением.':pending?'Результат '+(pending.kind==='sale'?'продажи':'сохранения')+' ещё не подтверждён. Корзина и данные защищены от изменения.':notice|| (state.capabilities?.atomic_cart!==true?'Новый каталог недоступен. Используйте обычную продажу одной позиции.':storageFailure?'Хранение черновика недоступно.':'');status.hidden=!status.textContent;alert.textContent=error||String(state.error||'');alert.hidden=!alert.textContent;}
 function validContext(){const rows=state.options||{};return Boolean(state.orgId&&state.actorId&&state.capabilities?.atomic_cart===true&&context.warehouseId&&context.sellerId&&context.paymentAccountId&&['cash','manual'].includes(context.paymentMethod)
  &&rows.sellers?.some(x=>x.id===context.sellerId&&x.active!==false)&&rows.paymentAccounts?.some(x=>x.id===context.paymentAccountId&&x.active!==false&&(context.paymentMethod!=='cash'||x.account_type==='cash'))
  &&(!context.clientId||rows.clients?.some(x=>x.id===context.clientId))&&(!context.bookingId||rows.bookings?.some(x=>x.id===context.bookingId&&(!context.clientId||x.client_account_id===context.clientId))));}
 function setContext(key,value){if(pending||busy||storageCorrupt)return;context[key]=value||null;if(key==='clientId'){context.bookingId=null;lines=[];notice='Клиент изменён. Корзина очищена для нового клиента.';serverErrors={};}if(key==='bookingId'&&value){const booking=state.options?.bookings?.find(row=>row.id===value);if(booking?.client_account_id)context.clientId=booking.client_account_id;}if(key==='paymentMethod')context.paymentAccountId=null;options.onContextChange?.({scope:scope(),context:clone(context)});persist();render();}
 function renderContext(){fields.replaceChildren();const rows=state.options||{};const definitions=[['clientId','Клиент',rows.clients||[],'Без клиента'],['bookingId','Визит',(rows.bookings||[]).filter(x=>!context.clientId||x.client_account_id===context.clientId),'Отдельная продажа'],['sellerId','Продавец',rows.sellers||[],'Выберите продавца'],['warehouseId','Склад',state.warehouses||[],'Выберите склад'],['paymentMethod','Оплата',[{id:'cash',name:'Наличные'},{id:'manual',name:'Вручную'}]],['paymentAccountId','Касса или счёт',(rows.paymentAccounts||[]).filter(x=>context.paymentMethod!=='cash'||x.account_type==='cash'),'Выберите кассу или счёт']];
  for(const [key,label,items,empty]of definitions){const select=selector(label,items.map(x=>({...x,disabled:x.active===false})),context[key],empty);select.disabled=Boolean(pending||busy||storageCorrupt);select.addEventListener('change',()=>setContext(key,select.value));fields.append(field(label,select));}
  const client=(rows.clients||[]).find(x=>x.id===context.clientId)?.name;settings.querySelector('summary').textContent=[client|| (context.clientId?'Клиент недоступен':'Без клиента'),(state.warehouses||[]).find(x=>x.id===context.warehouseId)?.name||'Выберите склад','Детали продажи'].join(' · ');
 }
 function choose(item){selected=item.id;editor=null;renderDialog(item);dialog.showModal();}
 function renderCatalog(){list.replaceChildren();const items=filterItems(state.items||[],filters);const count=node('p','cc-muted',items.length+' позиций');list.append(count);
  for(const item of items.slice(0,visibleLimit)){const row=node('article','cc-product');const open=button('','cc-product-open');open.dataset.catalogOpen=item.id;open.append(image(item));const copy=node('span','cc-product-copy');copy.append(node('strong','',item.name),node('small','cc-muted',[item.variant_label,item.sku,UNITS[item.sale_unit]].filter(Boolean).join(' · ')));open.append(copy);open.addEventListener('click',()=>choose(item));const meta=node('div','cc-product-meta');meta.append(node('strong','',money(item.sale_price_minor)));const stock=itemStock(item,state.balances,context.warehouseId);meta.append(node('small','cc-muted',stock===null?'Остаток неизвестен':'В наличии '+stock+' '+(UNITS[item.sale_unit]||'')));
   const add=button('+','cc-add');add.setAttribute('aria-label','Добавить '+item.name);const reason=itemProblem(item,'1',fullState());add.disabled=Boolean(!canWrite()||reason||state.capabilities?.atomic_cart!==true);add.title=reason||'Добавить в корзину';add.addEventListener('click',()=>{lines=addLines(lines,[{itemId:item.id,quantity:'1'}]);serverErrors={};persist();render();});
   const star=button(item.favorite?'★':'☆','cc-favorite');star.setAttribute('aria-label',(item.favorite?'Убрать из избранного: ':'В избранное: ')+item.name);star.setAttribute('aria-pressed',String(item.favorite===true));star.disabled=Boolean(!canWrite()||!options.onFavoriteChange);star.addEventListener('click',()=>void changeFavorite(item));row.append(open,meta,star,add);if(reason)row.append(node('small','cc-product-warning',reason));list.append(row);
  }
  if(!items.length)list.append(node('p','cc-empty',(state.items||[]).length?'Подходящих позиций нет. Измените поиск или фильтры.':'Каталог пока пуст. Добавьте свою позицию или выберите пример из библиотеки.'));
  if(items.length>visibleLimit){const more=button('Показать ещё '+Math.min(60,items.length-visibleLimit));more.addEventListener('click',()=>{visibleLimit+=60;renderCatalog();});list.append(more);}
  bundleList.replaceChildren();const bundles=(state.bundles||[]).filter(x=>x.active);if(bundles.length){bundleList.append(node('h4','','Товарные наборы'));for(const bundle of bundles){const row=node('div','cc-bundle-choice');const copy=node('div');copy.append(node('strong','',bundle.name),node('small','cc-muted',bundle.items.length+' товаров · состав можно изменить'));const add=button('Добавить');add.disabled=!canWrite()||state.capabilities?.bundles!==true;add.addEventListener('click',()=>{lines.push(bundleLine(bundle));persist();render();});row.append(copy,add);bundleList.append(row);}}
 }
 async function changeFavorite(item){const t=token();busy=true;render();try{const result=await options.onFavoriteChange({scope:scope(),itemId:item.id,favorite:!item.favorite});if(!current(t))return;if(result?.error)throw result.error;if(result?.inventory_item_id!==item.id||typeof result.favorite!=='boolean')throw new Error('invalid_favorite_response');state.items=state.items.map(x=>x.id===item.id?{...x,favorite:result.favorite}:x);}catch(e){if(current(t))report(e);}finally{if(current(t,false)){busy=false;render();}}}
 function editQuantity(line,value){if(!canWrite())return;line.quantity=value;line.unitChanged=false;serverErrors={};persist();renderCart();renderStatus();}
 function renderCart(){cart.replaceChildren();const evaluated=evaluateCart(lines,fullState());const heading=node('div','cc-cart-head');heading.append(node('h3','','Корзина'),node('span','cc-muted',String(lines.length)));cart.append(heading);
  if(!lines.length&&!pending)cart.append(node('p','cc-empty','Добавьте товары из каталога. Цена и остаток проверяются для выбранного склада.'));
  const cartList=node('div','cc-cart-list');for(const row of evaluated.rows){const block=node('div','cc-cart-row');block.dataset.lineId=row.lineId;const top=node('div','cc-cart-line-head');const title=row.bundleId?(state.bundles||[]).find(x=>x.id===row.bundleId)?.name||'Товарный набор':row.item?.name||'Недоступная позиция';top.append(node('strong','',title));const remove=button('Убрать','cc-text-button');remove.disabled=!canWrite();remove.addEventListener('click',()=>{lines=lines.filter(x=>x.lineId!==row.lineId);serverErrors={};persist();render();});top.append(remove);block.append(top);
   if(row.bundleId){for(const child of row.children)block.append(node('small','cc-muted',(child.item?.name||'Недоступная позиция')+' × '+child.quantity));const change=button('Изменить состав','cc-text-button');change.disabled=!canWrite();change.addEventListener('click',()=>{lines=lines.flatMap(x=>x.lineId===row.lineId?detachBundle(x):[x]);notice='Изменённый состав продаётся отдельными товарами.';persist();render();});block.append(change);}
   else if(row.item?.group_key){const variants=(state.items||[]).filter(x=>x.group_key===row.item.group_key);const variant=selector('Вариант '+title,variants.map(x=>({id:x.id,name:x.variant_label||x.name,disabled:!x.active})),row.itemId);variant.disabled=!canWrite();variant.addEventListener('change',()=>{const line=lines.find(x=>x.lineId===row.lineId);line.itemId=variant.value;serverErrors={};persist();render();});block.append(field('Вариант',variant));}
   const controls=node('div','cc-cart-quantity');const qty=input('Количество '+title,row.quantity);qty.inputMode='decimal';qty.disabled=!canWrite();qty.addEventListener('change',()=>editQuantity(lines.find(x=>x.lineId===row.lineId),qty.value));controls.append(field(row.bundleId?'Количество наборов':'Количество, '+(UNITS[row.item?.sale_unit]||''),qty),node('strong','',money(row.totalMinor)));block.append(controls);
   const message=serverErrors[row.lineId]||(row.unitChanged?'Единицы изменились: уточните количество.':row.problem);if(message)block.append(node('p','cc-line-error',message));cartList.append(block);
  }cart.append(cartList);
  if(pending){const recovery=node('div','cc-recovery');recovery.append(node('strong','','Сначала подтвердите результат'));const statusButton=button(pending.kind==='sale'?'Проверить продажу':'Проверить сохранение');statusButton.disabled=busy||!options.onResolvePending;statusButton.addEventListener('click',()=>void resolvePending('status'));const retry=button('Повторить тот же запрос');retry.disabled=busy||!options.onResolvePending;retry.addEventListener('click',()=>void resolvePending('retry'));recovery.append(statusButton,retry);cart.append(recovery);}
  const footer=node('div','cc-cart-footer');const total=button('','cc-total cc-total-toggle');total.setAttribute('aria-label','Показать корзину, '+lines.length+' позиций');total.addEventListener('click',()=>cart.scrollIntoView({block:'start',behavior:'smooth'}));total.append(node('small','cc-muted','Итого'),node('strong','',evaluated.totalMinor>0?money(evaluated.totalMinor):'—'));const submit=button(busy?'Подтверждаем…':'Провести продажу','cc-primary');submit.disabled=!canWrite()||!evaluated.valid||!validContext()||!options.onSubmit;submit.addEventListener('click',()=>void submitCart());footer.append(total,submit);cart.append(footer);
  if(lines.length&&!validContext()&&!pending)cart.append(node('p','cc-muted','Проверьте клиента, визит, продавца, склад и кассу в деталях продажи.'));
 }
 function renderActions(){actions.replaceChildren();const repeat=button('Повторить покупку');repeat.disabled=!canWrite()||!context.clientId||!options.onRepeat;repeat.addEventListener('click',()=>void repeatLast());actions.append(repeat);
  if(canManage()){for(const [label,handler]of [['Добавить товар',()=>openEditor()],['Библиотека примеров',openTemplates],['Импорт',openImport],['Создать набор',openBundleEditor]]){const b=button(label);b.disabled=!canWrite();b.addEventListener('click',handler);actions.append(b);}}
 }
 function render(){if(!alive)return;renderStatus();renderContext();renderActions();const cats=[...new Set((state.items||[]).map(x=>x.category).filter(Boolean))].sort();category.replaceChildren();const all=node('option','','Все категории');all.value='';category.append(all);for(const name of cats){const o=node('option','',name);o.value=name;category.append(o);}category.value=filters.category;renderCatalog();renderCart();}
 function closeDialog(){dialog.close();selected=null;editor=null;auxDraft=null;}
 function dialogHead(title){dialog.replaceChildren();const head=node('div','cc-dialog-head');const close=button('Закрыть');close.addEventListener('click',closeDialog);head.append(node('h3','',title),close);dialog.append(head);}
 function renderDialog(item){dialogHead(item.name);const content=node('div','cc-detail');content.append(image(item));const variants=item.group_key?(state.items||[]).filter(x=>x.group_key===item.group_key):[];
  if(variants.length>1){const select=selector('Вариант',variants.map(x=>({id:x.id,name:x.variant_label||x.name})),item.id);select.addEventListener('change',()=>{const next=state.items.find(x=>x.id===select.value);selected=next.id;renderDialog(next);});content.append(field('Вариант',select));}
  content.append(node('p','',item.description||'Описание пока не добавлено.'),node('p','cc-muted',[item.category,PURPOSES[item.purpose],item.sku?'Артикул '+item.sku:''].filter(Boolean).join(' · ')),node('strong','',money(item.sale_price_minor)));
  const qty=input('Количество','1');qty.inputMode='decimal';content.append(field('Количество, '+(UNITS[item.sale_unit]||''),qty));const errorEl=node('p','cc-line-error'),add=button('Добавить в корзину','cc-primary');const refresh=()=>{errorEl.textContent=itemProblem(item,qty.value,fullState());add.disabled=!canWrite()||Boolean(errorEl.textContent);};qty.addEventListener('input',refresh);add.addEventListener('click',()=>{if(add.disabled)return;lines=addLines(lines,[{itemId:item.id,quantity:qty.value}]);persist();closeDialog();render();});content.append(errorEl,add);
  if(canManage()){const edit=button('Изменить карточку');edit.disabled=!canWrite();edit.addEventListener('click',()=>openEditor(item));content.append(edit);}dialog.append(content);refresh();
 }
 async function repeatLast(){const t=token();busy=true;error='';render();try{const result=await options.onRepeat({scope:scope(),clientId:context.clientId});if(!current(t))return;if(result?.error)throw result.error;if(result?.organization_id!==state.orgId||result?.client_account_id!==context.clientId)throw new Error('commercial_client_mismatch');if(result.found!==true){notice='У выбранного клиента пока нет покупок товаров.';return;}
   // Use current catalog. Archived/missing items remain visible and block submission.
   const fresh=result.current_items||[],ids=new Set(fresh.map(x=>x.id));state.items=[...(state.items||[]).filter(x=>!ids.has(x.id)),...fresh];if(result.current_balances){const repeatedIds=new Set((result.lines||[]).map(x=>x.inventory_item_id));state.balances=[...(state.balances||[]).filter(x=>!repeatedIds.has(x.inventory_item_id)),...result.current_balances];}
   lines=repeatPurchase(result,fullState());serverErrors={};notice='Последняя покупка добавлена по текущим ценам. Проверьте остатки и недоступные позиции.';persist();
  }catch(e){if(current(t))report(e);}finally{if(current(t,false)){busy=false;render();}}}
 async function beginWrite(kind,payload,callback){if(!canWrite()||!callback)return;const t=token(),requestId=crypto.randomUUID();const exact=kind==='sale'?{...payload,p_request_id:requestId}:{...payload,requestId};pending=deepFreeze({kind,requestId,payload:clone(exact),createdAt:Date.now()});
  if(!persist()){pending=null;report('Хранение запроса недоступно. Ничего не отправлено.');render();return;}
  busy=true;error='';render();if(dialog.open)dialog.close();
  try{const outcome=await callback({scope:scope(),...(kind==='sale'?{intent:clone(exact)}:clone(exact))});if(!current(t,false))return;acceptOutcome(outcome);}catch(e){if(current(t,false))report(e);}finally{if(current(t,false)){busy=false;render();}}
 }
 function acceptOutcome(outcome){if(!pending)return false;
  if(outcome?.rolledBack===true&&outcome.requestId===pending.requestId&&outcome.organizationId===state.orgId){const e=outcome.error;serverErrors=lineErrors(e,lines);pending=null;persist();if(e)report(e);return false;}
  const confirmed=pending.kind==='sale'?outcome?.confirmed===true&&receiptMatches(pending,outcome.receipt,state.orgId):outcome?.confirmed===true&&outcome.requestId===pending.requestId&&outcome.organizationId===state.orgId;
  if(!confirmed){if(outcome?.error){serverErrors=lineErrors(outcome.error,lines);report(outcome.error);}else notice='Результат не подтверждён. Проверьте статус или повторите исходный запрос.';return false;}
  const kind=pending.kind;if(kind==='sale'&&!store.clear({confirmed:true})){notice='Продажа подтверждена, но защитные данные не удалось очистить. Повторная проверка использует тот же запрос.';return false;}pending=null;if(kind==='sale'){lines=[];serverErrors={};notice='Продажа подтверждена.';}else{notice='Сохранение подтверждено. Обновите каталог.';persist();}options.onConfirmed?.({scope:scope(),kind,outcome});return true;
 }
 async function submitCart(){if(!canWrite()||!validContext()||!evaluateCart(lines,fullState()).valid)return;await beginWrite('sale',buildIntent(lines,fullState(),null),options.onSubmit);}
 async function resolvePending(mode){if(!pending||busy||!options.onResolvePending)return;const t=token(),original=pending;busy=true;render();try{const result=await options.onResolvePending({scope:scope(),kind:original.kind,intent:clone(original.payload),requestId:original.requestId,mode});if(!current(t,false)||pending?.requestId!==original.requestId)return;acceptOutcome(result);persist();}catch(e){if(current(t,false))report(e);}finally{if(current(t,false)){busy=false;render();}}}
 function openEditor(item=null){if(!canWrite())return;editor=clone(item?{...item,inventory_item_id:item.id}:{inventory_item_id:null,metadata_version:0,name:'',sku:'',unit:'piece',sale_unit:'piece',stock_per_sale_unit:1,sale_price_minor:null,purpose:'retail',category:'',group_key:'',variant_label:'',icon:'box',photo_url:'',description:'',active:true});dialogHead(item?'Изменить карточку':'Добавить товар');const form=node('form','cc-editor');const controls={};
  const definitions=[['name','Название'],['sku','Артикул'],['category','Категория'],['group_key','Группа вариантов'],['variant_label','Название варианта'],['price','Цена, ₽'],['stock_per_sale_unit','Списываемый объём за одну единицу продажи'],['photo_url','Фото (HTTPS)']];
  for(const [key,label]of definitions){const control=input(label,key==='price'?editor.sale_price_minor===null?'':minorText(editor.sale_price_minor):editor[key]);if(key==='price'||key==='stock_per_sale_unit')control.inputMode='decimal';if(key==='name')control.required=true;if(['category','group_key'].includes(key))control.maxLength=80;controls[key]=control;form.append(field(label,control));}
  for(const [key,label,values]of [['purpose','Назначение',PURPOSES],['unit','Единица склада',UNITS],['sale_unit','Единица продажи',UNITS],['icon','Контурная иконка',ICONS]]){const control=selector(label,Object.entries(values).map(([id,name])=>({id,name})),editor[key]);if(key==='unit'&&editor.inventory_item_id)control.disabled=true;controls[key]=control;form.append(field(label,control));}
  const description=node('textarea');description.value=editor.description||'';description.maxLength=2000;description.rows=3;controls.description=description;form.append(field('Описание',description));const active=input('Активная позиция','','checkbox');active.checked=editor.active!==false;controls.active=active;form.append(field('Активная позиция',active));
  form.append(node('p','cc-muted','Остатки оформляются в складском учёте. Вариант — отдельная позиция со своим артикулом.'));const validation=node('p','cc-line-error');const save=button('Сохранить карточку','cc-primary');save.type='submit';save.disabled=!options.onSaveCatalog;form.append(validation,save);form.addEventListener('submit',event=>{event.preventDefault();if(!canWrite())return;const value={inventory_item_id:editor.inventory_item_id,metadata_version:editor.metadata_version};for(const [key,control]of Object.entries(controls)){if(key==='price')value.sale_price_minor=control.value.trim()?moneyMinor(control.value):null;else if(key==='stock_per_sale_unit')value[key]=decimal(control.value);else if(key==='active')value[key]=control.checked;else value[key]=control.value.trim();}const errors=validateItem(value,state.items||[]);if(controls.price.value.trim()&&value.sale_price_minor===null)errors.push('Цена: положительное число, до двух знаков после запятой.');validation.textContent=errors.join(' ');if(!errors.length)void beginWrite('item',{item:value},options.onSaveCatalog);});dialog.append(form);if(!dialog.open)dialog.showModal();}
 function openTemplates(){if(!canWrite())return;dialogHead('Библиотека примеров');dialog.append(node('p','cc-muted','Это примеры карточек. Выберите и отредактируйте нужную позицию; цена и остаток не создаются автоматически.'));const custom=button('Моё направление — своя позиция');custom.addEventListener('click',()=>openEditor());dialog.append(custom);for(const template of PROFESSION_TEMPLATES){const section=node('details','cc-template');section.append(node('summary','',template.name));for(const example of template.items){const b=button(example.name);b.addEventListener('click',()=>openEditor({...example,id:null,sku:'',description:'',active:true}));section.append(b);}dialog.append(section);}dialog.showModal();}
 function openBundleEditor(){if(!canWrite())return;dialogHead('Товарный набор');const form=node('form','cc-editor');const name=input('Название набора');name.maxLength=120;form.append(field('Название',name),node('p','cc-muted','Выберите 2–30 физических товаров. Набор не является пакетом услуг.'));const picks=node('div','cc-bundle-editor');const selectedRows=new Map();for(const item of (state.items||[]).filter(x=>x.active&&x.catalog_ready&&['retail','both'].includes(x.purpose))){const check=input('Включить '+item.name,'','checkbox'),qty=input('Количество '+item.name,'1');qty.inputMode='decimal';const row=node('div');row.append(field(item.name,check),qty);check.addEventListener('change',()=>{if(check.checked)selectedRows.set(item.id,qty);else selectedRows.delete(item.id);});picks.append(row);}form.append(picks);const msg=node('p','cc-line-error'),save=button('Сохранить набор','cc-primary');save.type='submit';save.disabled=!options.onSaveBundle;form.append(msg,save);form.addEventListener('submit',event=>{event.preventDefault();const items=[...selectedRows].map(([id,control])=>({inventory_item_id:id,quantity:decimal(control.value)}));const errors=[];if(name.value.trim().length<2)errors.push('Укажите название.');if(items.length<2||items.length>30)errors.push('Выберите 2–30 товаров.');for(const row of items){const item=state.items.find(x=>x.id===row.inventory_item_id);const q=scaled(row.quantity);if(q===null||q<=0n||['piece','pack'].includes(item.sale_unit)&&q%1000n)errors.push('Проверьте количество '+item.name+'.');}msg.textContent=errors.join(' ');if(!errors.length)void beginWrite('bundle',{bundleId:null,name:name.value.trim(),items,version:0},options.onSaveBundle);});dialog.append(form);dialog.showModal();}
 function openImport(){if(!canWrite())return;importState=null;dialogHead('Импорт карточек и цен');dialog.append(node('p','cc-muted','XLSX / CSV, до 200 строк. Остатки, количества и приход не импортируются. Сохранение доступно владельцу после проверки.'));const file=input('Файл импорта','','file');file.accept='.xlsx,.csv,.tsv';const body=node('div','cc-import');dialog.append(field('Файл',file),body);file.addEventListener('change',async()=>{const t=token();try{body.textContent='Читаем файл…';const sheets=await decodeCatalogFile(file.files?.[0],options.loadXlsx);if(!current(t)||!dialog.open)return;importState={sheets,sheetIndex:0,mapping:guessColumns(sheets[0]?.matrix[0]||[]),server:null};renderImport(body);}catch(e){if(current(t)&&dialog.open)body.textContent=e.message;}});dialog.showModal();}
 function renderImport(body){if(!importState)return;body.replaceChildren();const currentSheet=importState.sheets[importState.sheetIndex],matrix=currentSheet.matrix;if(importState.sheets.length>1){const sheet=selector('Лист',importState.sheets.map((x,i)=>({id:String(i),name:x.name})),String(importState.sheetIndex));sheet.addEventListener('change',()=>{importState.sheetIndex=Number(sheet.value);importState.mapping=guessColumns(importState.sheets[importState.sheetIndex].matrix[0]||[]);importState.server=null;renderImport(body);});body.append(field('Лист',sheet));}
  const mapping=node('details','cc-mapping');mapping.append(node('summary','','Сопоставить колонки'));const mappingFields=node('div','cc-context');for(const [key,label]of Object.entries(IMPORT_FIELDS)){const select=selector(label,(matrix[0]||[]).map((name,i)=>({id:String(i),name:String(name)})),String(importState.mapping[key]??-1),'Не импортировать');select.value=importState.mapping[key]>=0?String(importState.mapping[key]):'';select.addEventListener('change',()=>{importState.mapping[key]=select.value===''?-1:Number(select.value);importState.server=null;renderImport(body);});mappingFields.append(field(label,select));}mapping.append(mappingFields);body.append(mapping);
  const preview=previewImport(matrix,importState.mapping,state.items||[]);body.append(node('p','cc-muted',preview.rows.length+' строк · пустая цена остаётся неизвестной'));for(const message of preview.errors)body.append(node('p','cc-line-error',message));const table=node('div','cc-import-preview');for(const row of preview.rows){const block=node('div','cc-import-row');block.append(node('strong','',row.line+'. '+row.item.name),node('small','cc-muted',[row.operation,row.item.sku,money(row.item.sale_price_minor)].filter(Boolean).join(' · ')));for(const message of row.errors)block.append(node('p','cc-line-error',message));for(const e of importState.server?.errors||[])if(e.index===preview.rows.indexOf(row)+1)block.append(node('p','cc-line-error',friendlyError(e)));table.append(block);}body.append(table);
  const check=button('Проверить импорт');check.disabled=!preview.valid||busy||!options.onPreviewImport;const confirm=input('Подтверждаю сохранение карточек','','checkbox');const save=button('Сохранить импорт','cc-primary');save.disabled=true;const confirmedLabel=field('Я проверил строки и подтверждаю сохранение',confirm);confirm.addEventListener('change',()=>{save.disabled=!confirm.checked||state.role!=='owner'||!importState.server?.preview_hash||Boolean(importState.server?.errors?.length)||!canWrite();});
  check.addEventListener('click',async()=>{if(!preview.valid)return;const t=token();check.disabled=true;try{const result=await options.onPreviewImport({scope:scope(),rows:preview.rows.map(x=>x.item)});if(!current(t)||!dialog.open)return;if(result?.error)throw result.error;if(typeof result?.preview_hash!=='string'||!Array.isArray(result.rows)||!Array.isArray(result.errors))throw new Error('invalid_import_preview');importState.server=clone(result);renderImport(body);}catch(e){if(current(t))report(e);}finally{if(current(t)&&dialog.open)check.disabled=false;}});
  save.addEventListener('click',()=>{if(save.disabled||!confirm.checked||state.role!=='owner')return;void beginWrite('import',{rows:clone(preview.rows.map(x=>x.item)),previewHash:importState.server.preview_hash,confirmed:true},options.onCommitImport);});body.append(check);if(importState.server&&!importState.server.errors.length){body.append(node('p','cc-muted','Проверка сервера пройдена.'),confirmedLabel,save);}if(state.role!=='owner')body.append(node('p','cc-muted','Сохранить пакет импорта может только владелец.'));
 }
 render();
 return {
  update(next){if(!alive||next?.orgId!==state.orgId||next?.actorId!==state.actorId||next?.sessionKey!==state.sessionKey||!Number.isSafeInteger(next.revision)||next.revision<(state.revision||0))return false;state=clone(next);if(!pending&&next.context){if(Object.hasOwn(next.context,'clientId')&&(next.context.clientId||null)!==context.clientId){lines=[];context.bookingId=null;serverErrors={};}for(const key of CONTEXT_FIELDS)if(Object.hasOwn(next.context,key))context[key]=next.context[key]||null;}render();if(dialog.open&&selected&&!editor){const item=state.items?.find(x=>x.id===selected);if(item)renderDialog(item);else closeDialog();}return true;},
  destroy(){if(!alive)return;alive=false;epoch++;if(dialog.open)dialog.close();container.replaceChildren();},
  clearDraft({confirmedReceipt}={}){if(pending){if(!receiptMatches(pending,confirmedReceipt,state.orgId))return false;pending=null;}if(storageCorrupt)return false;lines=[];const ok=store.clear({confirmed:true});render();return ok;},
  getDraft:()=>clone({context,lines}),getPending:()=>pending?clone(pending):null,
 };
}
